### ISSUE TITLE
Hi, how can we choose to refresh only one page in wordpress with your plugin 

### ISSUE THREAD

**Issue by kodjoe** [jordanleven/wp-force-refresh#10]
Hi, how can we choose to refresh only one page in wordpress with your plugin ?
At this time I don't really understand why 3 pages on 8 are refreshed automatically ?
How can I choose which page to refresh with your plugin please ?

Thank you Jordan !!

**Comment by jordanleven** [comment]
@kodjoe,

There is a force refresh option on each page (https://wordpress.org/support/topic/can-we-refresh-part-of-the-website/).
