### ISSUE TITLE
Ability to refresh specific pages

### ISSUE THREAD

**Issue by jordanleven** [jordanleven/wp-force-refresh#2]
New feature would allow users to invoke refreshes on a specific page rather than site wide.

**Comment by batpoep** [comment]
Would love this ability! Thanks for adding it to the to-do list.

**Comment by jordanleven** [comment]
@batpoep No problem! Version 2.0 will be out this week and will include this feature. If you don't mind, could you leave a brief review on WordPress after it's out?

Thanks in advance!

Jordan
