### ISSUE TITLE
Button in Menu Bar

### ISSUE THREAD

**Issue by fnecreative** [jordanleven/wp-force-refresh#4]
How did I not know this existed until now? This is amazing! Thank you so very much for all of your hard work. 

Would you be able to add a button to the upper Wordpress menu? It would be nice to just go down the line of deleting the minified files, clearing the cache, and then BAM, the button for a force refresh. Maybe a simple thing because I'm so lazy, but this plugin is so amazing I want easy access to it. 

Thanks!

**Comment by jordanleven** [comment]
fnecreative,

Thanks! Just to clarify, are you looking to have a menu item in the sidebar of the WordPress admin to make it easier to navigate to the Force Refresh page?

**Comment by fnecreative** [comment]
<img width="1161" alt="screen shot 2018-05-11 at 7 12 13 pm" src="https://user-images.githubusercontent.com/39201312/39951409-46485dc6-554f-11e8-8797-7109bb0c3161.png">

I'm not sure if the screenshot will attach, but ideally on the top bar, right next to the site name, comments, add "new" section, and in my case, the cache clear plugin. So, if I could clear my cache and then immediately hit "force refresh" that would be great! At the very least, an option for it would be great. 

Thanks Jordan for all your hard work!

**Comment by jordanleven** [comment]
fnecreative,

Thanks for the clarification, this shouldn't be too crazy of a request. I'll probably have the ability to show this in the WP Admin Bar as an option since not everyone might want it to show up all the time. If enabled, the it would appear in the WP Admin Bar until the plugin is deactivated or the option is reserved.

I don't have an estimated turn around, but I'll let you know when this feature has been incorporated. Thanks again for your feedback!

**Comment by fnecreative** [comment]
That is exactly what I wanted! I really appreciate you taking the feedback. 

Thanks!!!!

**Comment by jordanleven** [comment]
Great! I'll go ahead and mark this as closed and, as always, a brief review or rating is always appreciated on the [Force Refresh plugin page](https://wordpress.org/support/plugin/force-refresh/reviews/). If you wanted to try out the beta before version 2.0, check out the below instructions.

Thanks!

Jordan

**Installing the Beta**
To download the beta version of Force Refresh, head over to the [Advanced page](https://wordpress.org/plugins/force-refresh/advanced/) of the plugin and scroll down to "Previous Versions." To download the beta, simply select the beta version (2.0.0-0) and click "Download". 

After downloading, deactivate your current version of Force Refresh from the plugins page and delete the plugin. After deactivating and deleting Force Refresh, upload the new version you just downloaded from WordPress.org and activate it. To confirm you're on the beta, the version number of the plugin will be the new version along with its build number (version 2.0.0-0).
