### ISSUE TITLE
conflict with the Absolute Privacy

### ISSUE THREAD

**Issue by atolloweb** [jordanleven/wp-force-refresh#6]
Hi!
I don't know if this is the right place to write this (if not, please tell me where to write feedbacks), but I found a conflict with the Absolute Privacy plugin (https://wordpress.org/plugins/absolute-privacy/).
In fact, every time the plugin is ON (no matter if is set on Complete Lockdown or Members Area), and I click on REFRESH, the site won't refresh.

I tested it with multiple devices at the same time, butit only works if you are logged in as administrator.
Is there a way to fix this?

Thanks!

**Comment by jordanleven** [comment]
Hey Atolloweb,

Thanks for the big report! I’m in the middle of moving so I can’t look at it right now, but I’ll be sure to reach out with a resolution or plugin update after I’ve identified the problem.
–

Jordan

**Comment by atolloweb** [comment]
Sure thing! No rush!
In the meantime, I started using s2member.  The entire site is now lockdown, and your plugin works just fine!
Focus on your moving now, it is more important :)

Bye!

**Comment by jordanleven** [comment]
Hey atolloweb,

Sorry it took me so long to get back to you! Moving is such a pain!

In any case, I downloaded the Absolute Privacy app you sent over and didn't see any conflicts with Force Refresh. I was able to successfully able to force a refresh with the plugin enabled. So as far as next steps with debugging go:

1. When you're logged into WordPress as an admin and click "Force Refresh", does it report a message like, "You've successfully requested all browsers to refresh (version xxx)"?
2. When you're on a page waiting for a refresh, do you see any errors in your browser console?
3. When you're on a page waiting for a refresh, have you checked the XHR section of your browser's network tab to see if the browser is reaching out to admin-ajax.php? You'd see a return like:
`{"success":true,"status_code":200,"status_text":"The current site version has been successfully retrieved.","return_data":{"current_site_version":"xxxxx"}}`

Let me know if you can return any of that information so I can investigate further! Thanks in advance!

**Comment by jordanleven** [comment]
Hey atolloweb,

Since I haven't heard back on this issue, I'm going to close it out for right now. If you continue to see the issue in the future, I can reopen it.
