### ISSUE TITLE
problem when I activate your plugin in wordpress

### ISSUE THREAD

**Issue by kodjoe** [jordanleven/wp-force-refresh#9]
Hi, i have a warning who block my website when your plugin is activate but can't find what is the problem. Here is the warning message: Warning:  Constants may only evaluate to scalar values in /home/.../wp-content/plugins/force-refresh/filter-force-refresh.php on line 30. Can you help me with this issue ? thanks a lot for your work !!

**Comment by jordanleven** [comment]
@kodjoe , it looks like you're running an older version of PHP. I'll be releasing an update soon that'll resolve this issue for you.

**Comment by kodjoe** [comment]
Hi that's weird because I have this message :"The plugin generated 184 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin." and here is my PHP version: Configuration, Version PHP globale -> 7.3

**Comment by jordanleven** [comment]
@kodjoe ,

I don't think you're on PHP 7.3. Non-scalar constants are supported from PHP 5.6 onwards (https://www.php.net/manual/en/language.constants.syntax.php) so it sounds like you're on a version prior to 5.6.

The message you're receiving ("The plugin generated 184 characters...") is expected if your PHP configuration is set to print notices, errors, and warnings to the page (typically something you don't do in production). This means that the warning message of non-scalar data being used in constants is throwing an error before the headers are sent, resulting in the second warning message.

**Comment by kodjoe** [comment]
you are totally right, I was app.engine.version=5.6 and now app.engine.version=7.1, thanks a lot for your information, all works fine now !!!!

**Comment by jordanleven** [comment]
Unable to reproduce (user error)
